import type { AnalysisResult } from '@/types/analysis';

export function exportReport(result: AnalysisResult) {
  const { research, score, verdict, technicalFit, timing, market, debate, outreach, confidence } = result;
  const vc = verdict.action === 'Pursue' ? 'pursue' : verdict.action === 'Nurture' ? 'nurture' : 'skip';

  const html = `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>VexIntel Report — ${research.companyName}</title>
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Space+Grotesk:wght@400;500;600;700&display=swap');
*{margin:0;padding:0;box-sizing:border-box}
body{background:#0a0b12;color:#d1d5e0;font-family:'Inter',sans-serif;padding:48px;max-width:800px;margin:0 auto;font-size:13px;line-height:1.7}
h1,h2,h3{font-family:'Space Grotesk',sans-serif}
h1{color:#39e5c0;font-size:24px;margin-bottom:2px}
.sub{color:#6b7090;font-size:12px;margin-bottom:32px}
h2{font-size:16px;color:#d1d5e0;margin-top:28px;margin-bottom:10px;padding-bottom:6px;border-bottom:1px solid #1c1e30}
.box{background:#12131d;border:1px solid #1c1e30;border-radius:6px;padding:16px;margin:10px 0}
.score{text-align:center;font-size:48px;font-weight:700;font-family:'Space Grotesk';color:#39e5c0}
.badge{display:inline-block;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:600}
.pursue{background:rgba(57,229,192,.1);color:#39e5c0}
.nurture{background:rgba(234,179,8,.1);color:#eab308}
.skip{background:rgba(239,68,68,.1);color:#ef4444}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}
.label{font-size:10px;text-transform:uppercase;letter-spacing:.1em;color:#5f6375;margin-bottom:2px}
.value{font-size:14px;font-weight:600}
.sig{font-size:12px;color:#8b8fa3;padding:3px 0;border-bottom:1px solid #1c1e30}
.footer{margin-top:40px;text-align:center;color:#3f4255;font-size:10px}
@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
</style></head><body>
<h1>VexIntel Intelligence Report</h1>
<p class="sub">${research.companyName} · ${research.domain} · ${research.industry} · ${new Date(result.timestamp).toLocaleDateString()}</p>

<div class="box" style="text-align:center">
<div class="score">${score.leadScore}</div>
<p style="color:#6b7090;font-size:12px">${score.category} Lead · ${confidence.overall}% Confidence</p>
<span class="badge ${vc}" style="margin-top:8px;display:inline-block">${verdict.action}</span>
</div>

<h2>Why Now</h2>
<div class="box"><p>${verdict.whyNow}</p></div>

<h2>Score Breakdown</h2>
<div class="grid">
<div class="box"><div class="label">Technical Fit</div><div class="value">${technicalFit.score}/10</div></div>
<div class="box"><div class="label">Timing</div><div class="value">${timing.timingScore}/10</div></div>
<div class="box"><div class="label">Budget</div><div class="value">${timing.budgetStrength}/10</div></div>
<div class="box"><div class="label">Market</div><div class="value">${market.marketPositionScore}/10</div></div>
</div>

<h2>Matched Services</h2>
<div class="box">${technicalFit.matchedServices.map(s => `<div class="sig"><strong>${s.service}</strong> (${s.relevance}/10) — ${s.reason}</div>`).join('')}</div>

<h2>Risk Factors</h2>
<div class="box">${verdict.riskFactors.map(r => `<div class="sig">⚠ ${r}</div>`).join('')}</div>

<h2>Agent Debate</h2>
<div class="box">
${debate.entries.map(e => `<div class="sig"><strong>${e.agent}</strong> (${e.sentiment}, ${e.confidence}%): ${e.position}</div>`).join('')}
<div style="margin-top:10px;color:#39e5c0;font-size:12px"><strong>Resolution:</strong> ${debate.resolution}</div>
</div>

<h2>Confidence</h2>
<div class="box">
<div class="sig">Overall: ${confidence.overall}% · Data: ${confidence.dataCompleteness}% · Agreement: ${confidence.agentAgreement}% · Evidence: ${confidence.evidenceStrength}%</div>
</div>

<h2>Outreach</h2>
<div class="box">
<div class="label">Target</div><p style="margin-bottom:12px">${outreach.decisionMakerPersona}</p>
<div class="label">Value Proposition</div><p>${outreach.valueProposition}</p>
</div>

<div class="footer">
<p>Generated by VexIntel — Autonomous Enterprise Intelligence Engine</p>
<p>Powered by DataVex · ${new Date().toISOString()}</p>
</div>
</body></html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const w = window.open(url, '_blank');
  if (w) w.onload = () => setTimeout(() => w.print(), 600);
}
